# Generated by Django 6.1.1 on 2026-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=80)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
